<?php

$this->headTitle('Cadastrar Usuário');

$this->userForm->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Nome',
    'required' => true,
    'autofocus' => true
])->setLabelAttributes([
    'class' => 'sr-only'
]);

$this->userForm->get('cpf')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'CPF',
    'required' => true,
    'autofocus' => true
])->setLabelAttributes([
    'class' => 'sr-only'
]);

$this->userForm->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Email',
    'required' => true,
    'autofocus' => true
])->setLabelAttributes([
    'class' => 'sr-only'
]);

$this->userForm->get('password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Senha',
    'required' => true,
    'autofocus' => true
])->setLabelAttributes([
    'class' => 'sr-only'
]);


$this->userForm->get('roles')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Role',
    'required' => true,
    'autofocus' => true
])->setLabelAttributes([
    'class' => 'sr-only'
]);

?>


<div class="row">
    <?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
    <?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
    <?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
</div>

<div class="row">
    <h1>Cadastrar Usuário</h1>
</div>
<div class="row justify-content-center">
    <div class="col-md-offset-4 col-md-12">
        <form method="post">

            <div class="form-group">
                <?= $this->formLabel($this->userForm->get('name')); ?>
                <?= $this->formElement($this->userForm->get('name')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($this->userForm->get('roles')); ?>
                <?= $this->formElement($this->userForm->get('roles')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($this->userForm->get('cpf')); ?>
                <?= $this->formElement($this->userForm->get('cpf')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($this->userForm->get('email')); ?>
                <?= $this->formElement($this->userForm->get('email')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($this->userForm->get('password')); ?>
                <?= $this->formElement($this->userForm->get('password')); ?>
            </div>

            <?= $this->formElement($this->userForm->get('csrf')) ?>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Cadastrar</button>
        </form>
    </div>
</div>