<?php

$this->headTitle('Listar Produtos');

?>

<div class="row">
    <?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
    <?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
    <?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
</div>

<div class="row">
    <a class="btn btn-success" href="<?= $this->url("admin/user", ["action" => "create"]) ?>">Cadastrar</a>
</div>
<br/>

<div class="row justify-content-center">
    <div class="col-md-12">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">CPF</th>
                <th scope="col">Email</th>
                <th scope="col">Roles</th>
                <th scope="col">Ações</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->users as $user): ?>
                <tr>
                    <th scope="row"><?= $user->getId() ?></th>
                    <td><?= $user->getName() ?></td>
                    <td><?= $user->getCpf() ?></td>
                    <td><?= $user->getEmail() ?></td>
                    <td><?= $user->getRoleAsString() ?></td>
                    <td><a href="<?= $this->url('admin/user', ['action' => 'show', 'id' => $user->getid()]) ?>">Visualizar</a>
                        | <a href="<?= $this->url('admin/user', ['action' => 'edit', 'id' => $user->getid()]) ?>">Editar</a>
                        | <a href="<?= $this->url('admin/user', ['action' => 'destroy', 'id' => $user->getid()]) ?>">Excluir</a></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>