<?php

$this->headTitle('Listar Roles');

?>

<div class="row">
    <?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
    <?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
    <?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
</div>

<div class="row">
    <a class="btn btn-success" href="<?= $this->url("admin/role", ["action" => "create"]) ?>">Cadastrar</a>
</div>
<br/>

<div class="row justify-content-center">
    <div class="col-md-12">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Descrição</th>
                <th scope="col">Layout</th>
                <th scope="col">Parent</th>
                <th scope="col">Ações</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->roles as $role): ?>
                <tr>
                    <th scope="row"><?= $role->getId() ?></th>
                    <td><?= $role->getName() ?></td>
                    <td><?= $role->getDescription() ?></td>
                    <td><?= $role->getLayout() ?></td>
                    <td><?= !is_null($role->getParent()) ? $role->getParent()->getName() : "" ?></td>
                    <td><a href="<?= $this->url('admin/role', ['action' => 'show', 'id' => $role->getid()]) ?>">Visualizar</a>
                        | <a href="<?= $this->url('admin/role', ['action' => 'edit', 'id' => $role->getid()]) ?>">Editar</a>
                        | <a href="<?= $this->url('admin/role', ['action' => 'destroy', 'id' => $role->getid()]) ?>">Excluir</a></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>