<?php

$this->headTitle('Definir Privilegios');

$this->privilegeForm->get('permissions')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Permissions',
    'required' => true,
    'autofocus' => true
])->setLabelAttributes([
    'class' => 'sr-only'
]);

$this->privilegeForm->get('resource')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Resource',
    'required' => true,
    'autofocus' => true
])->setLabelAttributes([
    'class' => 'sr-only'
]);

$this->privilegeForm->get('role')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Role',
    'required' => true,
    'autofocus' => true
])->setLabelAttributes([
    'class' => 'sr-only'
]);

?>


<div class="row">
    <?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
    <?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
    <?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
</div>

<div class="row">
    <h1>Cadastrar Privilegios</h1>
</div>
<div class="row justify-content-center">
    <div class="col-md-offset-4 col-md-12">
        <form method="post">

            <div class="form-group">
                <?= $this->formLabel($this->privilegeForm->get('permissions')); ?>
                <?= $this->formElement($this->privilegeForm->get('permissions')); ?>
            </div>


            <div class="form-group">
                <?= $this->formLabel($this->privilegeForm->get('resource')); ?>
                <?= $this->formElement($this->privilegeForm->get('resource')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($this->privilegeForm->get('role')); ?>
                <?= $this->formElement($this->privilegeForm->get('role')); ?>
            </div>

            <?= $this->formElement($this->privilegeForm->get('csrf')) ?>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Cadastrar</button>
        </form>
    </div>
</div>