<?php

$this->headTitle('Destroy Resource');

?>

<div class="row">
    <h1>Deseja Realmente Excluir esse Registro?</h1>
</div>
<br/>

<div class="row justify-content-center">
    <div class="col-md-12">
        <table class="table">
            <tbody>
            <tr>
                <th scope="row">#</th>
                <td><?= $this->privilege->getId() ?></td>
            </tr>
            <tr>
                <th scope="row">Role</th>
                <td><?= $this->privilege->getRole()->getName() ?></td>
            </tr>
            <tr>
                <th scope="row">Resource</th>
                <td><?= $this->privilege->getResource()->getName() ?></td>
            </tr>
            <tr>
                <th scope="row">Permissions</th>
                <td><?= $this->privilege->getPermissions() ?></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-4">
            <form name="category-form" method="post">
                <input type="hidden" name="id" value="<?= $this->privilege->getId() ?>">
                <button name="confirma" class="btn btn-danger">Confirmar</button>
            </form>
        </div>
        <div class="col-md-4 offset-md-1">
            <a class="btn btn-success" href="<?= $this->url("admin/privilege", ["action" => "index"]) ?>">Cancelar</a>
        </div>

    </div>
</div>